# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20161021_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, help_text='ZIP/Postcal code', max_length=10),
        ),
    ]
