# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 00:36
# IMPORTANT: This file was renamed on purpose to keep the same naming as release/python3, TODO: Check conflicts
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import djangoplicity.contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20190926_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='data_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=b'/home/noirlabadmin/shared/contacts_import'), upload_to=djangoplicity.contacts.models.handle_uploaded_file),
        ),
    ]
