# Generated by Django 2.2.16 on 2020-12-22 22:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20190926_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Social media'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='contactgroupaction',
            name='on_event',
            field=models.CharField(choices=[('contact_added', 'Contact added to group'), ('contact_removed', 'Contact removed from group'), ('contact_updated', 'Contact updated'), ('periodic_5min', 'Every 5 minutes'), ('periodic_30min', 'Every 30 minutes'), ('periodic_1hr', 'Every hour'), ('periodic_6hr', 'Every 6 hours'), ('periodic_24hr', 'Every day')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='max_display',
            field=models.IntegerField(default=25, help_text='Maximum number of duplicates to display at once.'),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='min_score_display',
            field=models.FloatField(default=0.7, help_text='Only display duplicates with score above this score.'),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('review', 'Review'), ('imported', 'Imported')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='data_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/home/hubbleadm/shared/contacts_import'), upload_to=djangoplicity.contacts.models.handle_uploaded_file),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('review', 'Review'), ('imported', 'Imported')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='importgroupmapping',
            name='mapping',
            field=models.ForeignKey(limit_choices_to={'field': 'groups'}, on_delete=django.db.models.deletion.CASCADE, to='contacts.ImportMapping'),
        ),
        migrations.AlterField(
            model_name='importmapping',
            name='group_separator',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='duplicate_handling',
            field=models.CharField(choices=[('none', 'Import all - no duplicate detection'), ('smart', 'Detect duplicates and wait for review')], default='smart', max_length=20),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='frozen_groups',
            field=models.ManyToManyField(blank=True, help_text='Contacts belonging to these groups will not be updated.', related_name='importtemplate_frozen_set', to='contacts.ContactGroup'),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='tag_import',
            field=models.BooleanField(default=True, help_text='Create a contact group for this import.'),
        ),
        migrations.AlterField(
            model_name='label',
            name='paper',
            field=models.CharField(choices=[('a4-l7163', 'A4 (L7163 - 99.1x38.1)'), ('a4-l7165', 'A4 (L7165 - 99.1x67.7)'), ('us-letter-5162', 'US Letter (5162 - 102x34)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='region',
            name='local_name',
            field=models.CharField(max_length=200, verbose_name='Region/State name in the local language'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Region/State name'),
        ),
    ]
