# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-07 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20201222_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, help_text='ZIP/Postcal code', max_length=50),
        ),
    ]
