# Generated by Django 3.1 on 2022-09-12 10:22

import django.core.files.storage
from django.db import migrations, models
import djangoplicity.contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20201222_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='data_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='/home/noirlabadmin/shared/contacts_import'), upload_to=djangoplicity.contacts.models.handle_uploaded_file),
        ),
    ]
