# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20151214_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'processing', b'Processing'), (b'review', b'Review'), (b'imported', b'Imported')], default=b'new', help_text=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='import',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'processing', b'Processing'), (b'review', b'Review'), (b'imported', b'Imported')], default=b'new', help_text=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='importtemplate',
            name='duplicate_handling',
            field=models.CharField(choices=[(b'none', b'Import all - no duplicate detection'), (b'smart', b'Detect duplicates and wait for review')], default=b'smart', help_text=b'', max_length=20),
        ),
    ]
