# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 14:00
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import djangoplicity.contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20170203_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='data_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=b'/app/shared/contacts_import'), upload_to=djangoplicity.contacts.models.handle_uploaded_file),
        ),
    ]
